# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_round', models.IntegerField(default=1)),
                ('victories_player_one', models.IntegerField(default=0)),
                ('victories_player_two', models.IntegerField(default=0)),
                ('result', models.CharField(choices=[(b'1', b'Player 1 Wins!'), (b'2', b'Player 2 Wins!'), (b'3', b'Draw!'), (b'4', b'Pending!')], default=4, max_length=1)),
                ('finished', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lta', models.BooleanField(verbose_name=b'Is LTA?')),
                ('last_lta', models.DateField(blank=True, null=True, verbose_name=b'Last LTA')),
                ('ltas', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rounds', models.IntegerField(default=1)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='player_one',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_one', to='tournaments.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_two',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_two', to='tournaments.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tournaments.Player'),
        ),
    ]
