# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(to='tournaments.Player'),
        ),
    ]
