# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20151203_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
