# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20151203_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bye_times',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
    ]
