# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_auto_20151203_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bye_times',
            field=models.IntegerField(default=0),
        ),
    ]
