# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_auto_20151203_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tournaments.Player'),
        ),
    ]
